import { getResearchSession } from "@/app/actions/research"
import { RichTextEditor } from "@/components/editor/rich-text-editor"
import { AutoPrint } from "@/components/research/auto-print"
import { notFound } from "next/navigation"

export default async function ReadResearchPage({
    params,
    searchParams,
}: {
    params: Promise<{ id: string }>
    searchParams: Promise<{ [key: string]: string | string[] | undefined }>
}) {
    const { id } = await params
    const { print } = await searchParams
    const session = await getResearchSession(id)

    if (!session) {
        notFound()
    }

    return (
        <div className="min-h-screen bg-background">
            <div className="max-w-[210mm] mx-auto bg-white min-h-screen shadow-lg p-12 print:shadow-none print:p-0">
                <div className="mb-8 print:hidden">
                    <h1 className="text-4xl font-bold mb-2 text-black">{session.title}</h1>
                    <div className="text-sm text-gray-500">
                        Generated by Unislyd Research Assistant
                    </div>
                </div>

                <div className="reader-mode [&_.ProseMirror]:min-h-0 [&_.ProseMirror]:p-0">
                    <RichTextEditor
                        content={session.editor_content}
                        readOnly={true} // Explicitly set as true
                        className="border-none shadow-none"
                    />
                </div>
            </div>
            {print === 'true' && <AutoPrint />}
        </div>
    )
}
