import { getResearchSession } from "@/app/actions/research"
import { RichTextEditor } from "@/components/editor/rich-text-editor"
import { notFound } from "next/navigation"

export default async function ReadResearchPage({ params }: { params: { id: string } }) {
    const session = await getResearchSession(params.id)

    if (!session) {
        notFound()
    }

    return (
        <div className="min-h-screen bg-background">
            <div className="max-w-[210mm] mx-auto bg-white min-h-screen shadow-lg p-12 print:shadow-none print:p-0">
                <div className="mb-8 print:mb-4">
                    <h1 className="text-4xl font-bold mb-2 text-black">{session.title}</h1>
                    <div className="text-sm text-gray-500">
                        Generated by Unislyd Research Assistant
                    </div>
                </div>

                <div className="reader-mode [&_.ProseMirror]:min-h-0 [&_.ProseMirror]:p-0">
                    <RichTextEditor
                        content={session.editor_content}
                        onChange={() => { }}
                        readOnly={true}
                        className="border-none shadow-none"
                    />
                </div>
            </div>
            {/* Print trigger using script since we want it to auto-print if parameter is set, 
                but simpler just to let user use browser print or we add a button if needed. 
                For "Download PDF", opening this page and printing to PDF is standard web behavior. 
            */}
        </div>
    )
}
